# Generated by Django 3.2.25 on 2024-10-08 05:35

import categories.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='preview',
            field=models.ImageField(default='', max_length=200, upload_to=categories.models.shops_directory_path),
        ),
        migrations.AddField(
            model_name='products',
            name='shop',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='categories.shops'),
        ),
        migrations.AddField(
            model_name='products',
            name='short_description',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
