# Generated by Django 3.2.25 on 2024-11-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20241125_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='time_finish',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='time_start',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
