# Generated by Django 3.2.25 on 2024-11-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_auto_20241125_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='time_finish',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='time_start',
            field=models.DateTimeField(null=True),
        ),
    ]
