# Generated by Django 3.2.25 on 2025-04-01 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_auto_20241125_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vlogs',
            options={'verbose_name': 'Vlog', 'verbose_name_plural': 'Vlogs'},
        ),
    ]
