# Generated by Django 3.2.25 on 2025-05-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_alter_vlogs_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='name_kr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
