# Generated by Django 3.2.25 on 2025-05-02 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_auto_20250502_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='name_kr',
            new_name='name_ko',
        ),
    ]
