# Generated by Django 3.2.25 on 2025-05-15 02:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_rename_name_kr_categories_name_ko'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='shops',
            name='description_ko',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='shops',
            name='info_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='shops',
            name='info_ko',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='shops',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shops',
            name='name_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shops',
            name='short_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shops',
            name='short_description_ko',
            field=models.TextField(null=True),
        ),
    ]
