# Generated by Django 3.2.25 on 2025-05-15 03:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0011_auto_20250515_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='description_ko',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='name_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='short_description_en',
            field=ckeditor.fields.RichTextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='short_description_ko',
            field=ckeditor.fields.RichTextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='title_ko',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
