# Generated by Django 3.2.25 on 2025-05-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0015_auto_20250525_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopslocations',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
