# Generated by Django 3.2.25 on 2025-04-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('denied', 'Denied'), ('ready', 'Payed')], default='accepted', max_length=30),
        ),
    ]
